/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-error-container": "#93000a",
                "surface-container-high": "#dce9ff",
                "inverse-primary": "#a7cfbf",
                "on-secondary": "#ffffff",
                "on-primary-fixed-variant": "#294e41",
                "surface-container-lowest": "#ffffff",
                "status-error": "#EF4444",
                "surface-container-highest": "#d3e4fe",
                "surface-container-low": "#eff4ff",
                "primary-fixed-dim": "#a7cfbf",
                "tertiary-fixed-dim": "#bdcac1",
                "inverse-surface": "#213145",
                "on-error": "#ffffff",
                "on-background": "#0b1c30",
                "tertiary-container": "#1f2a25",
                "secondary-fixed": "#aaf859",
                "on-surface": "#0b1c30",
                "surface-tint": "#416658",
                "primary-fixed": "#c3ebda",
                "surface-container": "#e5eeff",
                "on-primary-container": "#719788",
                "error-container": "#ffdad6",
                "outline": "#717975",
                "primary-container": "#062e23",
                "surface-bg": "#F8FAFC",
                "on-secondary-fixed": "#0e2000",
                "error": "#ba1a1a",
                "inverse-on-surface": "#eaf1ff",
                "secondary-fixed-dim": "#90db3f",
                "primary": "#001810",
                "on-tertiary-fixed": "#131e19",
                "tertiary-fixed": "#d9e6dd",
                "on-secondary-container": "#407100",
                "status-success": "#10B981",
                "on-primary": "#ffffff",
                "surface-dim": "#cbdbf5",
                "on-primary-fixed": "#002117",
                "outline-variant": "#c1c8c3",
                "secondary": "#3c6a00",
                "on-tertiary-fixed-variant": "#3e4943",
                "tertiary": "#0a1510",
                "status-warning": "#F59E0B",
                "background": "#f8f9ff",
                "surface": "#f8f9ff",
                "on-secondary-fixed-variant": "#2c5000",
                "on-tertiary-container": "#85928a",
                "on-surface-variant": "#414845",
                "secondary-container": "#aaf859",
                "surface-bright": "#f8f9ff",
                "border-muted": "#E2E8F0",
                "on-tertiary": "#ffffff",
                "surface-variant": "#d3e4fe"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "table-cell-py": "12px",
                "stack-lg": "32px",
                "container-margin": "24px",
                "base": "4px",
                "stack-sm": "8px",
                "stack-md": "16px",
                "gutter": "16px",
                "table-cell-px": "16px"
            },
            "fontFamily": {
                "mono-data": ["Hanken Grotesk", "sans-serif"],
                "body-lg": ["Hanken Grotesk", "sans-serif"],
                "headline-lg-mobile": ["Manrope", "sans-serif"],
                "display-lg": ["Manrope", "sans-serif"],
                "body-sm": ["Hanken Grotesk", "sans-serif"],
                "headline-md": ["Manrope", "sans-serif"],
                "headline-lg": ["Manrope", "sans-serif"],
                "label-md": ["Hanken Grotesk", "sans-serif"],
                "body-md": ["Hanken Grotesk", "sans-serif"]
            },
            "fontSize": {
                "mono-data": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
        },
    },
    plugins: [],
};
